### ISSUE TITLE
add pictures to site

### ISSUE THREAD

**Issue by annamorphism** [dact-chant/hildegard#1]
Currently all pictures are a placeholder. 
I have the pictures previously uploaded to the site & will upload these to the repo.

**Comment by annamorphism** [comment]
@dchiller apparently I need push access to the repo in order to add the image files...

**Comment by dchiller** [comment]
Just made you an admin!

**Comment by annamorphism** [comment]
Past me wrote (in 2022):
"Now every page has an image; I also sized them so that the first bibliography entry appears "above the fold" (at least on my screen), though now I am not sure if I like how it looks. (Otherwise the images automatically size so that the text and image width align, which means vertical images are just a sea of picture before you get to the content.) I also gave them all an alt-text/hover text; if you have opinions about those, let me know. (I couldn't remember which print the image of Hildegard was taken from, for example.)"
Subsequently Jennifer requested captions be added.
So some other subtasks:

- [ ] add alt-text
- [ ] Size images properly
- [ ] Add captions/citations

**Comment by annamorphism** [comment]
Revisiting this conversation is also reminding me which pictures went with what, and how they should be cited:

Monographical: I think this was the Scivias image. Per Jennifer, "The Scivias Codex image should be described as the Abtei St-Hildegard copy of the original: https://abtei-st-hildegard.de/%e2%80%9cscivias%e2%80%9d-kodex-tafel-9-die-chore-der-engel/"

Historical-Biographical: This was an image of Hildegard's profession currently in the Hildegard museum (I think?), a copy of the relief in the Binger Rochuskapelle by Jakob Busch 1898.

Relics:  This is hildegard-relics.jpg: "The Shrine image is taken from here:
https://www.bingen.de/en/hildegard/searching-for-traces/catholic-parish-church
The actual name of the church is: Katholische Pfarrkirche St. Hildegard"

General: I believe this was the little woodcut of Hildegard. Per Jennifer: The “16th-century book” is actually 15th century: it’s Hartmann Schedel’s Weltchronik, but the Latin version (one was published in Latin and the other in German): https://www.historisches-lexikon-bayerns.de/Lexikon/Schedelsche_Weltchronik
Hartmann Schedel, Liber chronicarum ab O. C. (Nuremberg: Koberger, 1493), and Das Buch der Croniken und Geschichten: Weltchronik (Nuremberg: Koberger, 1493)

Medical: I toyed with several images here, but settled on an image of Physicas from the Hildegard museum, 
physicas-lower-res.jpg, which is a personal photograph.

**Comment by annamorphism** [comment]
Fixed by PR #10.
